Feature/Create Block Button Repeat
B8ND-winter-project/alimo-android pull request #71
Opened 2024-04-26 06:03 UTC by wnsgur1

2024-04-29 10:02 UTC, 8954sood requested changes

2024-04-29 10:02 UTC, 8954sood commented on app/src/main/java/com/b1nd/alimo/presentation/feature/fcm/FirebaseMessageService.kt
> +            .setSmallIcon(R.drawable.frame_239) // 알림 아이콘
drawable의 요소들의 이름을 아이콘이면 ic로 통일해주세요.

2024-04-29 10:02 UTC, 8954sood commented on app/src/main/java/com/b1nd/alimo/presentation/feature/onboarding/parent/join/first/ParentJoinFirstViewModel.kt
> +    val isButtonClicked = _isButtonClicked.asStateFlow()
변수명 대로라면 기본값이 false여야 할것 같습니다.

2024-04-29 10:02 UTC, 8954sood commented on app/src/main/java/com/b1nd/alimo/presentation/feature/onboarding/parent/join/second/ParentJoinSecondViewModel.kt
> +    val isButtonClicked = _isButtonClicked.asStateFlow()
위와 같습니다.

2024-04-29 10:02 UTC, 8954sood commented on app/src/main/java/com/b1nd/alimo/presentation/feature/onboarding/parent/join/second/ParentJoinSecondViewModel.kt
> +                                            _isButtonClicked.value = true
delay를 거는 이유가 있나요?

2024-04-29 10:03 UTC, wnsgur1 commented on app/src/main/java/com/b1nd/alimo/presentation/feature/onboarding/parent/join/first/ParentJoinFirstViewModel.kt
> +    val isButtonClicked = _isButtonClicked.asStateFlow()
이걸 기본값으로 false를 해버리면 처음에 클릭 조차 되지않아 true로 하였습니다.

2024-04-29 10:05 UTC, wnsgur1 commented on app/src/main/java/com/b1nd/alimo/presentation/feature/onboarding/parent/join/second/ParentJoinSecondViewModel.kt
> +                                            _isButtonClicked.value = true
버튼을 누르고 delay를 넣어야 연타가 방지 되지않나요?

2024-04-29 10:08 UTC, wnsgur1 commented on app/src/main/java/com/b1nd/alimo/presentation/feature/fcm/FirebaseMessageService.kt
> +            .setSmallIcon(R.drawable.frame_239) // 알림 아이콘
변경했습니다

2024-04-29 10:14 UTC, 8954sood commented on app/src/main/java/com/b1nd/alimo/presentation/feature/onboarding/parent/join/first/ParentJoinFirstViewModel.kt
> +    val isButtonClicked = _isButtonClicked.asStateFlow()
xml 쪽에서 !vm. isButtonClicked를 하면 되지않을까요?

2024-04-29 10:14 UTC, 8954sood commented on app/src/main/java/com/b1nd/alimo/presentation/feature/onboarding/parent/join/second/ParentJoinSecondViewModel.kt
> +                                            _isButtonClicked.value = true
딜레이는 상관 없고, 통신이 끝났을 떄 isButtonClicked의 상태를 변경하면 됩니다. 
isButtonCliked의 상태에 따라 버튼의 활성화 여부가 변경되는 겁니다.

2024-04-29 10:16 UTC, wnsgur1 commented on app/src/main/java/com/b1nd/alimo/presentation/feature/onboarding/parent/join/second/ParentJoinSecondViewModel.kt
> +                                            _isButtonClicked.value = true
인정합니다. 통신이 끝난후 쓸모없는 딜레이를 넣은거 같습니다.

2024-04-29 10:25 UTC, wnsgur1 commented on app/src/main/java/com/b1nd/alimo/presentation/feature/onboarding/parent/join/first/ParentJoinFirstViewModel.kt
> +    val isButtonClicked = _isButtonClicked.asStateFlow()
기본값 변경하였습니다.

2024-04-30 05:22 UTC, 8954sood approved these changes
수고하셨습니다 :)

2024-04-30 05:22 UTC, merged